# Generated by Django 3.1.2 on 2020-10-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.TextField(default=''),
        ),
    ]
